# Site Settings
title: Sophie Engbert
description: My Portfolio
url: "https://yourusername.github.io"

# Theme
theme: jekyll-theme-slate
# Build settings
markdown: kramdown

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
